ci: adding workflow for release a new version of the helm file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,4 +27,27 @@ jobs:
                 for chart in ./; do
                     helm install test-release "$chart" --dry-run
                 done
-            
+    success:
+        needs:
+            - linting-and-testing
+        if: >- # run if at least one needed job has failed or all needed jobs have not been cancelled or skipped
+            always() && (
+                contains(join(needs.*.result, ','), 'failure')
+                || (
+                !contains(join(needs.*.result, ','), 'cancelled') 
+                && !contains(join(needs.*.result, ','), 'skipped')
+                )
+            )
+        runs-on: ubuntu-24.04
+        steps:
+        - name: Verify no failures occurred in needed jobs
+            # if there are failures, false is executed and the job fails.
+            run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
+    
+    deploy:
+        needs:
+            - success
+        uses: ./.github/workflows/release.yml
+        if: github.ref_name == github.event.repository.default_branch
+        secrets: inherit
+    
